version: '3.4'

services:
  mysql:
    image: mysql:5.7
    #ports:
    #  - '3306:3306'
    volumes:
      - ./packages/public/server/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin
  #  links:
  #    - mysql:db
  #  ports:
  #    - '8080:80'

  node:
    build:
      context: .
      dockerfile: packages/private/node-image/Dockerfile

  workspace:
    build:
      context: .
      dockerfile: packages/private/workspace-image/Dockerfile
    depends_on:
      - node

  editor-renderer:
    build:
      context: .
      dockerfile: packages/public/editor-renderer/Dockerfile
    depends_on:
      - workspace

  legacy-editor-renderer:
    build:
      context: .
      dockerfile: packages/public/legacy-editor-renderer/Dockerfile
    depends_on:
      - workspace

  server-composer:
    image: composer:1.8
    volumes:
      # For macOS, add `:cached` to every volume for improved performance, see also https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - ./packages/public/server/composer.json:/app/composer.json:cached
      - ./packages/public/server/composer.lock:/app/composer.lock:cached
      - ./packages/public/server/src/vendor:/app/src/vendor:cached

  server-composer-dev-tools:
    image: composer:1.8
    volumes:
      # For macOS, add `:cached` to every volume for improved performance, see also https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - ./packages/public/server/dev-tools/composer.json:/app/composer.json:cached
      - ./packages/public/server/dev-tools/composer.lock:/app/composer.lock:cached
      - ./packages/public/server/dev-tools/vendor:/app/vendor:cached

  server-httpd:
    build:
      context: packages/public/server
      dockerfile: docker/httpd/Dockerfile
      target: base
    ports:
      - '4567:80'
    volumes:
      # For macOS, add `:delegated` to every volume for improved performance, see also https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - ./packages/public/server/src/public:/usr/local/apache2/htdocs/src/public:delegated
    environment:
      - PHP_HOST=server-php

  server-php:
    build:
      context: packages/public/server
      dockerfile: docker/php/Dockerfile
      target: base
    volumes:
      # For macOS, add `:delegated` to every volume for improved performance, see also https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - ./packages/public/server/dev-tools/vendor:/usr/local/apache2/htdocs/dev-tools/vendor:delegated
      - ./packages/public/server/package.json:/usr/local/apache2/htdocs/package.json:delegated
      - ./packages/public/server/php-cs-fixer.config.php:/usr/local/apache2/htdocs/php-cs-fixer.config.php:delegated
      - ./packages/public/server/phpunit.xml:/usr/local/apache2/htdocs/phpunit.xml:delegated
      - ./packages/public/server/src/config:/usr/local/apache2/htdocs/src/config:delegated
      - ./packages/public/server/src/lang:/usr/local/apache2/htdocs/src/lang:delegated
      - ./packages/public/server/src/module:/usr/local/apache2/htdocs/src/module:delegated
      - ./packages/public/server/src/public:/usr/local/apache2/htdocs/src/public:delegated
      - ./packages/public/server/src/test:/usr/local/apache2/htdocs/src/test:delegated
      - ./packages/public/server/src/vendor:/usr/local/apache2/htdocs/src/vendor:delegated
      - ./packages/public/server/src/init_autoloader.php:/usr/local/apache2/htdocs/src/init_autoloader.php:delegated

  static-assets:
    image: nginx
    ports:
      - '8082:80'
    volumes:
      # For macOS, add `:delegated` to every volume for improved performance, see also https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - ./packages/public/static-assets/src:/var/share/nginx/html:delegated
