js: &js
  docker:
    - image: circleci/node:10

php: &php
  docker:
    - image: circleci/php:7.0.33

yarn_restore_cache: &yarn_restore_cache
  keys:
    - yarn-v1-{{ checksum "yarn.lock" }}
    - yarn-v1-
yarn_save_cache: &yarn_save_cache
  key: yarn-v1-{{ checksum "yarn.lock" }}
  paths:
    - ~/.cache/yarn
yarn_install: &yarn_install
  command: yarn --frozen-lockfile

composer_restore_cache: &composer_restore_cache
  keys:
    - composer-v1-{{ checksum "packages/server/composer.lock" }}
    - composer-v1-
composer_save_cache: &composer_save_cache
  key: composer-v1-{{ checksum "packages/server/composer.lock" }}
  paths:
    - .packages/server/src/vendor
composer_install: &composer_install
  command: (cd packages/server && composer install --no-interaction --dev --prefer-dist)

composer_dev_restore_cache: &composer_dev_restore_cache
  keys:
    - composer-v1-{{ checksum "packages/server/dev-tools/composer.lock" }}
    - composer-v1-
composer_dev_save_cache: &composer_dev_save_cache
  key: composer-v1-{{ checksum "packages/server/dev-tools/composer.lock" }}
  paths:
    - .packages/server/dev-tools/vendor
composer_dev_install: &composer_dev_install
  command: (cd packages/server/dev-tools && composer install --no-interaction --dev --prefer-dist)

version: 2.1
jobs:
  build:
    <<: *js
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          <<: *yarn_restore_cache
      - run:
          <<: *yarn_install
      - save_cache:
          <<: *yarn_save_cache
      - run:
          command: yarn build
  js:test:
    <<: *js
    steps:
      - checkout
      - restore_cache:
          <<: *yarn_restore_cache
      - run:
          <<: *yarn_install
      - save_cache:
          <<: *yarn_save_cache
      - run:
          command: yarn test
  php:test:
    <<: *php
    steps:
      - checkout
      - restore_cache:
          <<: *composer_restore_cache
      - run:
          <<: *composer_install
      - save_cache:
          <<: *composer_save_cache
      - run:
          command: .packages/server/src/vendor/bin/phpunit
  js:lint:
    <<: *js
    steps:
      - checkout
      - restore_cache:
          <<: *yarn_restore_cache
      - run:
          <<: *yarn_install
      - save_cache:
          <<: *yarn_save_cache
      - run:
          command: yarn lint
  php:lint:
    <<: *php
    steps:
      - checkout
      - restore_cache:
          <<: *composer_dev_restore_cache
      - run:
          <<: *composer_dev_install
      - save_cache:
          <<: *composer_dev_save_cache
      - run:
          command: .packages/server/dev-tools/vendor/bin/php-cs-fixer fix --config=php-cs-fixer.config.php --dry-run

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - js:test
      - php:test
      - js:lint
      - php:lint
